# This template is intended to make it fast to migrate 1UP Team's AWS Lambda projects into GitHub Actions successfully
# Please consider you might need to tweak a few commands to make your project migration into GitHub Actions successfully

# Add the following secrets from the repository settings: UP_AWS_ACCESS_KEY_ID, UP_AWS_SECRET_ACCESS_KEY, UP_SLACK_WEBHOOK_URL

# You also will need to add specific tests and steps to test your project (e.g. Python, Java)

name: 1UP - Build AWS Lambda

on:
  push:
    branches:
      - "*"
      - "**/*"

jobs:
  build_sbt_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/setup-sam@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.UP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.UP_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build - SAM
        run: sam build

      - name: Release - [on master]
        if: github.ref == 'refs/heads/master'
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      - name: Report - setup [on master]
        if: always() && github.ref == 'refs/heads/master'
        run: |
          GIT_COMMIT_MSG=$(git log -1 --pretty=format:'%s')
          GIT_COMMIT_MSG_NO_SUFFIX="${GIT_COMMIT_MSG#*\(#}"
          GIT_PR="${GIT_COMMIT_MSG_NO_SUFFIX%\)*}"
          GIT_REPO_URL="https://github.com/${{ github.repository }}"
          GIT_PR_URL="$GIT_REPO_URL/pull/$GIT_PR"
          GIT_REPO_NAME="${{ github.repository }}"
          echo "GIT_ACTIONS_URL=<$GIT_REPO_URL/actions/runs/${{ github.run_id }}|${GIT_REPO_NAME#*/}>" >> $GITHUB_ENV
          [[ "$GIT_PR" =~ ^[0-9]+$ ]] && GIT_PR_MSG="<$GIT_PR_URL|$GIT_COMMIT_MSG>" || GIT_PR_MSG="$GIT_COMMIT_MSG"
          echo "GIT_PR_MSG=$GIT_PR_MSG" >> $GITHUB_ENV

      - name: Report - success [on master]
        uses: Ilshidur/action-slack@2.0.2
        if: success() && github.ref == 'refs/heads/master'
        env:
          SLACK_WEBHOOK: ${{ secrets.UP_SLACK_WEBHOOK_URL }}
          SLACK_CUSTOM_PAYLOAD: '{"channel": "1up-releases", "attachments":[{"color": "#2eb886", "blocks":[{"type":"section","text":{"type":"mrkdwn","text": "{{ GIT_ACTIONS_URL }} released\n{{ GIT_PR_MSG }}"}}]}]}'
      - name: Report - failure [on master]
        uses: Ilshidur/action-slack@2.0.2
        if: failure() && github.ref == 'refs/heads/master'
        env:
          SLACK_WEBHOOK: ${{ secrets.UP_SLACK_WEBHOOK_URL }}
          SLACK_CUSTOM_PAYLOAD: '{"channel": "1up-releases",  "attachments":[{"color": "#ed2f00", "blocks":[{"type":"section","text":{"type":"mrkdwn","text": ":boom: {{ GIT_ACTIONS_URL }} failed!\n{{ GIT_PR_MSG }}"}}]}]}'
