# This template is intended to make it fast to migrate 1UP Team's SBT projects into GitHub Actions
# Please consider you might need to tweak a few commands to make your project migration into GitHub Actions

# Replace the following environment variables: APP_NAME
# Add the following secrets from the repository settings: UP_AWS_ACCESS_KEY_ID, UP_AWS_SECRET_ACCESS_KEY, UP_SLACK_WEBHOOK_URL

name: 1UP - Build SBT

on:
  push:
    branches:
      - *

env:
  APP_NAME: your-app-name
  IMAGE_TAG: b${{ github.run_number }}-${{ github.sha }}
  ECR_REPOSITORY: 933782373565.dkr.ecr.eu-west-1.amazonaws.com


jobs:
  build_sbt_project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2

      - name: SBT Test
        run: sbt clean test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.UP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.UP_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Publish docker image to ECR
        if: github.ref == 'refs/heads/master'
        run: ./sbt docker:publish
        env:
          BUILD_VERSION: ${{ env.IMAGE_TAG }}
          GITHUB_PKG_USER: ${{ secrets.ACTOR }}
          GITHUB_PKG_TOKEN: ${{ secrets.TOKEN }}

      - uses: silinternational/ecs-deploy@master
        if: github.ref == 'refs/heads/master'
        with:
          aws_access_key_cmd: '--aws-access-key'
          aws_access_key: ${{ secrets.UP_AWS_ACCESS_KEY_ID }}
          aws_secret_key_cmd: '--aws-secret-key'
          aws_secret_key: ${{ secrets.UP_AWS_SECRET_ACCESS_KEY }}
          cluster_cmd: '--cluster'
          cluster: 'up-cluster-production'
          image_cmd: '--image'
          image: ${{ env.ECR_REPOSITORY }}/${{ APP_NAME }}:${{ IMAGE_TAG }}
          region_cmd: '--region'
          region: 'eu-west-1'
          service_name_cmd: '--service-name'
          service_name: 'replace-me-with-service-name'
          timeout_cmd: ${{ env.APP_NAME }}
          timeout: '3600'

      - name: Report Status
        if: always() && github.ref == 'refs/heads/master'
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.UP_SLACK_WEBHOOK_URL }}
